version: "3.9"

services:
  backend:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "3000:3000"



  frontend:
    container_name: react
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend



